### PR TITLE
Webcomponents (with shadow dom) support

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by jogibear9988** [comment]
@xontab any thoughts about this commit?

**Comment by AlexMold** [comment]
@xontab Can you republish your chrome extension with last git repo updates ???
Thanks.

**Comment by jogibear9988** [comment]
you can use the git repo directly as a chrome extension

**Comment by AlexMold** [comment]
@jogibear9988 but in prod ? :(

**Comment by jogibear9988** [comment]
You can create a crx with chrome wich you can use in prod

**Comment by almightykiwi** [comment]
@xontab Can you have a look at this PR?

FYI, dispatching "input" events also improves compatibility with AngularJS.
I second the idea of a new release with those changes.

**Pull request merged**
